### ISSUE TITLE
find github settings to allow more than one assignee per issue in a repository

### ISSUE THREAD

**Issue by juliacollins** [nsidc/granule-metgen#19]
@juliacollins From a quick search this seems nothing that you will be able to change but has to do with our subscription:

"Issues and pull requests in public repositories, and in private repositories for a paid account, can have up to 10 people assigned. Private repositories on the free plan are limited to one person per issue or pull request."

**Comment by juliacollins** [comment]
`granule-metgen` is now a public repository, so you should be able to assign multiple people to issues.

**Comment by lisakaser** [comment]
Thanks for figuring this out and changing the repo to public
