### ISSUE TITLE
Create granule-metgen CLI app with configuration

### ISSUE THREAD

**Issue by eigenbeam** [nsidc/granule-metgen#30]
Create a `granule-metgen` CLI app that:

1. Is installable 
2. Can be invoked with individual commandline arguments for configuration
3. Can be invoked with a commandline argument for the file where configuration exists
4. Starts up, summarizes the current configuration, stop

**Comment by lisakaser** [comment]
Acceptance criteria:

Scenario: Installation
Given: The Operator installs the app
Then: ...? (@eigenbeam What is the message for a successful installation?)

Scenario: Help
Given: The operator runs the app
When: the operator uses the instameta help command
Then: The following or similar text will display:

 ❯ instagram --help
Usage: instagram [OPTIONS]

Options:
  --config TEXT  Instagram configuration file
  --help         Show this message and exit.

**Comment by lisakaser** [comment]
@eigenbeam please add additional acceptance criteria/scenarios that will be use cases for Amy to test once this issue is handed to her for testing.

**Comment by eigenbeam** [comment]
@afitzgerrell The instructions in the README in the Requirements, Installation, and Usage sections should give the concrete steps to test this issue. See: https://github.com/nsidc/granule-metgen/blob/main/README.md

**Comment by afitzgerrell** [comment]
I re-read the README.md this morning after you spiffed it up. I have one more suggestion: in the Usage section, following the second bullet, i think it'd be helpful to add a bullet to say:

- Exit the Poetry shell:
`$ exit`

...and one further question: with it installed/runnable on my laptop, is this something that once in production, i'd want to so any sort of $ git "refresh" (inserting the actual command there) to make sure i have the latest version of the tool running? if so, that would be another bullet i'd suggest adding to the Usage section.

**Comment by eigenbeam** [comment]
Done!

Regarding production, we will have (at that time) a different--and easier--way to install it, upgrade versions, etc. When we get to that ticket(s) we'll update the install and usage instructions.
