### ISSUE TITLE
Allow operator to select a local science data file location

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#33]
1 story point

Acceptance criteria:
Scenario 1

Given: App is installed
When: user runs "init" and enters science data file location
Then: App writes out config file with this value

Scenario 2

Given: App is installed
When: user creates ini file with a science data file location in it; 
then: running app with info shows content of ini file

Scenario 3:

Given: App is installed
When: user runs "help"
Then: explanatory text <- Amy will give feedback on if more/less info is needed

**Comment by afitzgerrell** [comment]
Question, Scenario 1:
`When: user runs "init" and enters science data file location`
`Then: App writes out config file with this value
`
I think maybe this meant to say "user runs app `init`, with the --config option specifying the path to, and name of, the .ini file (including the .ini suffix) to be created." So, this is what i did. Then I populated info: data directory, ARN, and s3 bucket.

Scenario 2: yes, completed successfully running `app info --config ./example/0081.ini`.

Scenario 3: success, technically though i ran `app --help`, not `app help`.

What follows may be outside the scope of this story, it would be helpful if (at some point, when appropriate) the help text also explained following the commands details:
...
 info     Summarizes the values in a metgen configuration file.
 init     Creates a new metgen config file based on user input.
 process  Processes science data files based on a metgen configuration.

For detailed help on command options, run `app <command name> --help`.

**Comment by lisakaser** [comment]
@afitzgerrell I am sending this back to @eigenbeam to edit the help text before we close this ticket.

**Comment by juliacollins** [comment]
@afitzgerrell @eigenbeam I am a chaos agent. I had already made some help text changes to the branch `issue-39`, so I incorporated Amy's suggestions above to that branch. When you review the issues #39 and #49 please confirm the help text meets your needs.
