### ISSUE TITLE
Allow operator to select a Kinesis stream where the CNM file is posted

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#34]
1 story point

Acceptance criteria:
Scenario 1

Given: App is installed
When: user runs "init" and enters kinesis stream
Then: App writes out config file with this value

Scenario 2

Given: App is installed
When: user creates ini file with a kinesis stream in it;
then: running app with info shows content of ini file

Scenario 3:

Given: App is installed
When: user runs "help"
Then: explanatory text <- Amy will give feedback on if more/less info is needed

**Comment by afitzgerrell** [comment]
Done! I have no feedback beyond the comments I added to #33.

**Comment by lisakaser** [comment]
🎉
