### ISSUE TITLE
Allow ARN patterns to be used instead of full values 

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#37]
1 story point

Add code that reads config and looks up the Kinesis stream and S3 bucket (Examples in OA)

Acceptance review:
Operator can provide an environment agnostic pattern for AWS Kinesis and S3 resources.

**Comment by eigenbeam** [comment]
After starting this ticket, I realized we can do two things:

1. Use just the stream name, not the full AWS ARN, to specify the Kinesis stream we will publish to
2. Use the ${environment} in the stream name, which will get replaced with whatever environment the operator has specified when running metgenc.

The example/modscg.ini file has been updated to show how this works now.

**Comment by lisakaser** [comment]
Amy completed test and no questions/problems came up, so I am closing this ticket.
