### ISSUE TITLE
Create template for CNM message in JSON format

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#39]
1 story point

Acceptance criteria:

Visual inspection of CNM message and JSON format by Amy

**Comment by juliacollins** [comment]
@afitzgerrell here's some sample output. The contents of the init file used in this experiment are:

```
[Source]
data_dir: ./data/modscgdrf

[Collection]
auth_id: NSIDC-FOOBAR
version: 1
provider: FORTYTWO

[Destination]
local_output_dir: ./json
ummg_dir = ummg
kinesis_arn: abcd-1234-wxyz-0666
```

From the command line: `instameta process --config example/template.ini --env=hoo`   I used hoo as the environment so you could see where it ends up in the s3 urls. :-)

Resulting CNM output is in the attached files (you may need to reformat/use a pretty printer):

[h08v05_Terra_20220415.v2023.1.nc.cnm.json](https://github.com/user-attachments/files/16802748/h08v05_Terra_20220415.v2023.1.nc.cnm.json)
[h07v03_Terra_20220415.v2023.1.nc.cnm.json](https://github.com/user-attachments/files/16802749/h07v03_Terra_20220415.v2023.1.nc.cnm.json)

**Comment by juliacollins** [comment]
@afitzgerrell I created two template files: one for the "body" of the CNM message which applies to all CNM content for a given collection, and one that can be repeated for the multiple files associated with a collection (including the UMM-G file).

The body content:

```
{
    "version": "1.5.1",
    "submissionTime": "$submission_time",
    "identifier": "$uuid",
    "collection": "$auth_id",
    "provider": "$provider",
    "product": {
        "name":  "$producer_granule_id",
        "dataVersion": "$version",
        "files": []
    }
}

```

The files content (repeated for each file):

```
{
    "name": "$file_name",
    "type": "$file_type",
    "uri": "$staging_uri",
    "checksumType": "$checksum_type",
    "checksum": "$checksum",
    "size": $file_size
}
```

**Comment by juliacollins** [comment]
@afitzgerrell a few notes to guide your review:

- The terms beginning with a `$` in the template files will be replaced with the actual values for a given dataset.
- To see the files in their native habitat, update your working directory (notes on that step below) and look in `<path-to-your-copy-of-granule-metgen>/src/nsidc/metgen/templates`

To update your copy of the code base:

- `cd path-to-your-copy-of-granule-metgen`
-  See if you've made any changes to files that might collide with changes in the remote repository: `git status` "Untracked" files don't matter.
- Make sure you're on the `main` branch and update your local copy: `git checkout main; git pull`
- Checkout the branch where I'm making changes: `git checkout issue-39`

That _should_ do it, but let me know if you're not seeing the expected updates.

**Comment by afitzgerrell** [comment]
Everything worked and checks out well!
