### ISSUE TITLE
Moving data files and UMM-G files to selected destination

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#40]
3 story points

acceptance criteria:
given: we have science files and a config file 
when: operator runs MetGenC
then: science files and UMM-G files get copied to the S3 bucket with the correct full name

if: S3 bucket is not found or transfer fails
then: create useful error message

Questions:
- Data files and UMM-G both go to the same staging bucket? ->yes,  info in CNM files
- Do files go into root of the staging bucket or into specific path? -> no paths, info in CNM files

**Comment by afitzgerrell** [comment]
I first tested to verify that if I run MetGenC to point at directories where I have two files + their associated umm-g, and my config file is set up appropriately, I'm able to see the data files and umm-g files hit Amazon S3 > Buckets > nsidc-cumulus-uat-ingest-staging > external/ > NSIDC-0081DUCk/ > 2/ and look as I'd expect them to.

Second, if I test with an incorrectly set up ini file, (i.e., goofy staging bucket name), MetGenC reports:
--------------------------------------------------
The configuration is invalid:
 * The staging bucket does not exist.

Unable to process data: Invalid configuration

**Comment by lisakaser** [comment]
🎉
