### ISSUE TITLE
Collect all UMM-G required values for [data set] and writes them out in UMM-G and JSON file format  (each science file one JSON file).

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#45]
5 story points

Acceptance criteria:

Scenario

GIVEN: App installed and example ini & science file available 
When: Run the app with TBD command line option
THEN: Will generate UMM-G file
Visually inspect output for correctness/completeness

**Comment by juliacollins** [comment]
Sigh...attached to wrong issue. One moment...

**Comment by afitzgerrell** [comment]
i’ve had a look at the output umm-g and cnm files’ content and, for sanity’s sake, double checked the checksums/file sizes (just for one of the two future-granules), and all looks great.

**Comment by lisakaser** [comment]
🎉
