### ISSUE TITLE
Operator can use stored credentials for AWS

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#46]
5 story points

acceptance criteria:
As operator I can run the tool and it will retrieve the valid AWS credentials from environment variables and publish CNM message to Kinesis stream.
App will have to message that credentials were retrieved successfully and cnm messages are posted.
Appropriate error messages if there are no credentials or not valid credentials.
Note in README how and what environment variables to set up.

**Comment by juliacollins** [comment]
A few notes from the CMR mediator arena:

- The application currently uses  the `puppet-nsidc-vault-client` puppet module to interact with the NSIDC Vault instance when provisioning a VM.
- During the provisioning process, passwords are retrieved from Vault and stored in a credentials.rb file on the new VM.
- `cmr-mediator` also requires a Launchpad certificate for _CMR write_ purposes. We shouldn't need to worry about this unless Launchpad authentication is somehow involved in staging files to Cumulus.
- Note that some experimental "vault-in-docker" work is happening (see the `vault-in-docker` project on Bitbucket).
- The current `vagrant-nsidc` credentials tarball includes a Vault key pair, presumably to allow access to the Vault API. Apparently `vagrant-nsidc` v13.1.0 no longer uses the credentials tarball, but instead pulls information directly from Vault. Mike L. will need to provide more background on how this magical Vault access is implemented.

**Comment by eigenbeam** [comment]
We decided to rely on the user to setup their AWS configuration & credentials using the standard AWS directory and files. The instructions on how to do this are in the README after issue-38 is done.

If this is sufficient, then this issue can be tested after issue-38 is done.

**Comment by lisakaser** [comment]
Closing issue as issue 38 was successfully tested which means this one is tested indirectly as well.
