### ISSUE TITLE
Determine a good, netCDF-compliant file to use as a dev/test case in lieu of modscgdrf_nrt

### ISSUE THREAD

**Issue by afitzgerrell** [nsidc/granule-metgen#54]
From a data set currently ingested to ECS, determine a netCDF-compliant file with a gpolygon spatial representation that crosses the anti-meridian to be used for testing purposes from here forward.

Note: considering a trait common amongst all of NSIDC's PS or EASE-2 polar data sets are spatial representations that both cross the anti-meridian and include one of earth's poles, focusing on a PM or MEaSUREs (possibly an ICESat-2 gridded file?) is likely best.

**Comment by afitzgerrell** [comment]
I suggest that we use Near-Real-Time DMSP SSMIS Daily Polar Gridded Sea Ice Concentrations V2 (NSIDC-0081). It's netCDF compliant, has only a few imperfections which are overlookable though. 

Truth be told, a perfectly structured data set doesn't exist in our archive yet that's gpolygon, will cross the anti-meridian, encompass one pole or the other, and is in a netCDF data format...MODSCGDRF_NRT is gonna be the one to say "hold my beer" pretty soon though!!

**Comment by afitzgerrell** [comment]
Fitz todo: ask CARP team if it's ok if we use its UAT environment is ok for us to potentially clobber? Or, do we need a staging environment set up?

**Comment by lisakaser** [comment]
@afitzgerrell lets discuss this question with Troy on Thursday if we can use the UAT environment for this data set or if they can create us a higher version of the data set that we can play with that will never become public or if he has an other idea for a test environment for DUCk.

**Comment by lisakaser** [comment]
Troy suggested creating a test record that we duplicate from NSIDC-0081 (e.g. NSIDC-0081DUCk) that we can work with. We will only work with CUAT and CPROD environments.
