### ISSUE TITLE
Create testing environment

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#57]
- Troy will check PIVs from Amy, Kevin, Julia (If needed Daniel will create a NAMS request)
- Environments: only UAT, PROD are needed for DUCk
-  Lisa will ask TW (Theresa) to clone existing record (only cumulus record not ECS!) - make sure record is in test state and not get published so we dont create a landing page accidentally
- Lisa will ask Cathy or Operator (Marin) to push record to CMR
- Operator (Amy and Cathy/Marin)set up dashboard (need to set it up the same way as NSIDC-0081) - set ACLs
- DUCk team (Amy) create some sample files - simple duplicate NSIDC-0081 files and rename them with new AUTHID
- Suggested AUTHID name: NSIDC-0081DUCk
- Where should sample files live: in staging environment (mount staging to VM)
- Troy will ask Mike D if we can use NSIDC external Kinesis stream (the one for MODSCGDRF_NRT)

**Comment by eigenbeam** [comment]
Test data: http://staging-http.apps.int.nsidc.org/staging/SAMPLE_DATA/DUCk_project/

**Comment by lisakaser** [comment]
Description of metgenc test plan as posted on the #cumulus slack channel developed by DUCk team in discussion with Troy, et al.:

- We have a Collection setup in the UAT environment with a short name of NSIDC-0081DUCk.
- For metgenc testing that does not involve invoking and running the corresponding Cumulus workflow for NSIDC-0081DUCk, we should test in Cumulus SBX or the NSIDC AWS account. For these tests we would create a DUCk-specific Kinesis stream and s3 bucket(s) where we could connect, send messages, and move files.
- For metgenc testing that does involve invoking and running the corresponding Cumulus workflow for NSIDC-0081DUCk  (integration tests), we will connect to the Cumulus UAT account and use the standard Cumulus Kinesis stream and s3 bucket(s).
- Before running integration tests, we should notify / coordinate with the Cumulus team by posting in the #cumulus slack channel.
- Amy Fitz will be getting up-to-speed with Cumulus and will be our go-to Ops person for anything Cumulus related during our metgenc integration tests. I.e., checking that we correctly invoked the workflow, verifying the workflow success, and diagnosing workflow failure.
- It is our understanding that as long as we notify #cumulus slack channel that we are doing integration tests in UAT, we can send messages to Kinesis and move files to s3 and this should not distract from other work in the UAT Cumulus account.
- We also understand that the Cumulus team may be doing deploys throughout this PI and we may not be able to do integration tests at these times.

**Comment by lisakaser** [comment]
Above description on test plans was also added to the DUCk team confluence page: https://nsidc.atlassian.net/wiki/spaces/DAACSW/pages/361201665/Cumulus+Direct+Ingest+Metadata+and+Transfer+Files+Tool+Development+Project+DICe-UMMG-CNM+FY2024+25
