### ISSUE TITLE
Assess whether granulemeta is useful for this project.

### ISSUE THREAD

**Issue by juliacollins** [nsidc/granule-metgen#6]

**Comment by juliacollins** [comment]
Review notes:

High level summary: Half of`granulemeta` might be relevant to our workflow for the use cases in which we need to read data (science) files and extract information, but the output doesn't support our needs. Additionally, the code for specific data file types is integrated into the tool's code base, and we'd like to figure out a flexible way to add new "file type readers" in a less-tightly-coupled fashion.

`granulemeta` writes an output file containing information about _all_ granules in a collection, one granule per line in CSV format. The workflow doesn't map directly to our proposed architecture, since we need to create a UMM-G file for each granule.

Geospatial information is conveyed by way of well-known text and proj4 summary strings, but no GeoJSON (Gpolygon) content is included in the output table entry for each granule. We would have to add additional processing steps to generate individual UMM-G files, and would need to add GPolygon details for the datasets requiring that form of geospatial representation.

The code base might be useful as a reference example for:

- Parsing NetCDF4 files (and other file types such as raster, vector, archive)
- Configuration file management
- Command line argument handling
- Directory navigation and filename parsing
- Creating MD5 checksum
- Retrieving file size

**Comment by lisakaser** [comment]
Thanks @juliacollins 
Tagging @eigenbeam for awareness and closing the issue
