### ISSUE TITLE
Generate UMM-G and CNM mock files

### ISSUE THREAD

**Issue by juliacollins** [nsidc/granule-metgen#7]
Meet with DPT to walk through content in sample UMM-G and CNM files.

**Comment by juliacollins** [comment]
Hannah created the files h08v05_Terra_20220415.v2023.1.json (UMM-G) and h08v05_Terra_20220415.v2023.1_cnm.json (CNM). I'd added these to the `granule-metgen` repository for future reference, along with a couple of other files that represent the initial mockup attempt. See https://github.com/nsidc/granule-metgen/tree/main/json

**Comment by juliacollins** [comment]
Data files associated with the example JSON files have also been added to the `granule-metgen` repository

**Comment by lisakaser** [comment]
Great!
