### ISSUE TITLE
find new test new data set

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#91]
Determine a (or more) new data(s) set for DUCk to run through the MetGenC rigors.

**Comment by afitzgerrell** [comment]
Outside of NSIDC, I found that PODAAC has some tiled data in netCDF that are cf-compliant (based on running cfchecks utility): [GHRSST Level 2P NOAA STAR SST v2.80 from VIIRS on S-NPP Satellite](https://search.earthdata.nasa.gov/search/granules?p=C2147480877-POCLOUD&pg[0][v]=f&pg[0][id]=20241119074000-STAR-L2P_GHRSST-SSTsubskin-VIIRS_NPP-ACSPO_V2.80-v02.0-fv01.0&pg[0][gsk]=-start_date&fdc=Physical%2BOceanography%2BDistributed%2BActive%2BArchive%2BCenter%2B%2528PO.DAAC%2529&gdf=NetCDF&tl=1732047442!3!!&lat=29.25&long=-159.75&zoom=0)

**Comment by afitzgerrell** [comment]
I've added the IRTIT3 v2 files to /disks/sidads_staging/SAMPLE_DATA/DUCk_project/IRTIT3_DUCk. The entire data set comprises 5 files, so I went ahead and placed a copy of each there.

**Comment by lisakaser** [comment]
I am closing this issue as the work is done and we can keep this issue as information place for the future.
